# pytest.ini
[pytest]
minversion = 7.0
addopts = --cov=src --cov-report=lcov:lcov.info --cov-report=term -n 2
pythonpath = src
log_cli = 1
log_cli_level = INFO
log_cli_format = %(asctime)s [%(levelname)8s] %(message)s (%(filename)s:%(lineno)s)
log_cli_date_format=%Y-%m-%d %H:%M:%S
markers =
    serial: mark tests to run in serial since the -n xdist switch runs tests in parallel (deselect with '-m "not slow"')
    integration: mark integration tests
; mock_use_standalone_module = true
env_files = .env
