import { notFound } from "next/navigation";
import { marked } from "marked";
import { getArtifact } from "@/lib/atlas/artifacts";
import { ArtifactToolbar } from "@/components/atlas/ArtifactToolbar";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";

type Props = { params: Promise<{ id: string }> };

const PAGE_CSS = `
  .artifact-wrap { font: 15px/1.65 -apple-system,Segoe UI,Roboto,Helvetica,Arial,sans-serif;
    max-width: 820px; margin: 40px auto; padding: 0 24px; color: #1a202c; background: #fff; }
  .artifact-head { border-bottom: 2px solid #3a4ff7; padding-bottom: 12px; margin-bottom: 8px; }
  .artifact-head h1 { font-size: 24px; margin: 0 0 4px; }
  .artifact-meta { color: #718096; font-size: 12px; }
  .artifact-body h2 { font-size: 19px; margin-top: 28px; color: #3a4ff7; }
  .artifact-body h3 { font-size: 16px; color: #3a4ff7; }
  .artifact-body a { color: #3a4ff7; }
  .artifact-body code { background: #f0f2f7; padding: 2px 5px; border-radius: 4px; font-size: 13px; }
  .artifact-body pre { background: #f0f2f7; padding: 14px; border-radius: 8px; overflow-x: auto; }
  .artifact-body table { border-collapse: collapse; width: 100%; margin: 12px 0; }
  .artifact-body th,.artifact-body td { border: 1px solid #e2e8f0; padding: 6px 10px; text-align: left; }
  .artifact-body thead th { background: #f0f2f7; }
  .artifact-body blockquote { border-left: 3px solid #3a4ff7; margin: 12px 0; padding-left: 14px; color: #4a5568; }
  .artifact-foot { margin-top: 40px; padding-top: 12px; border-top: 1px solid #e2e8f0; color: #a0aec0; font-size: 12px; }
  @media print { .no-print { display: none !important; } .artifact-wrap { margin: 0; max-width: none; } }
`;

export default async function ArtifactPage({ params }: Props) {
  const { id } = await params;
  const a = await getArtifact(id);
  if (!a) notFound();
  const html = marked.parse(a.body_md, { async: false }) as string;
  const when = new Date(a.created_at).toISOString().slice(0, 10);

  return (
    <div className="artifact-wrap">
      <style dangerouslySetInnerHTML={{ __html: PAGE_CSS }} />
      <div className="artifact-head">
        <h1>{a.title}</h1>
        <div className="artifact-meta">CSL Atlas · graph-grounded research · {when}</div>
      </div>
      <ArtifactToolbar id={a.id} />
      <div className="artifact-body" dangerouslySetInnerHTML={{ __html: html }} />
      <div className="artifact-foot">Generated by CSL Atlas. Verify source-cited facts before acting.</div>
    </div>
  );
}
