from enum import Enum


class PromptTitle(Enum):
    NAMED_ENTITY_EXTRACTION = 0
    SUMMARIZE_INDUSTRY = 1
    BUSINESS_VALUE = 2
    MONETARY_VALUE = 3
    TOP_QUESTIONS = 4
    ENRICH = 5
    KNOWLEGE_GRAPH_EXTRACTION = 20
    KNOWLEGE_GRAPH_SUMMARY = 21
    KNOWLEGE_GRAPH_COMMUNITY_SUMMARY = 22
