import "server-only";
import { marked } from "marked";
import {
  Document,
  Packer,
  Paragraph,
  TextRun,
  HeadingLevel,
} from "docx";
import { query } from "./db";

/**
 * Published artifacts — a saved, shareable snapshot of an answer.
 *
 * Mirrors Claude's "Publish": the owner turns an answer into a stable page at
 * /nextgen/a/<id> that anyone who can reach the app can view and download as
 * Markdown, HTML, Word (.docx) or PDF (browser print of the page). Everything
 * is generated on-box with pure-JS libraries — no cloud calls, so it works in
 * the no-egress VPC.
 */

export interface Artifact {
  id: string;
  user_id: string;
  conversation_id: string | null;
  title: string;
  body_md: string;
  source: string | null;
  revoked: boolean;
  created_at: string;
}

export async function createArtifact(
  userId: string,
  input: { title: string; bodyMd: string; source?: string | null; conversationId?: string | null }
): Promise<Artifact> {
  const rows = await query<Artifact>(
    `INSERT INTO artifacts (user_id, conversation_id, title, body_md, source)
     VALUES ($1, $2, $3, $4, $5)
     RETURNING *`,
    [
      userId,
      input.conversationId ?? null,
      (input.title || "Untitled").slice(0, 200),
      input.bodyMd ?? "",
      input.source ?? null,
    ]
  );
  return rows[0];
}

/** Public fetch (by id) — returns null when missing or revoked. */
export async function getArtifact(id: string): Promise<Artifact | null> {
  const rows = await query<Artifact>(
    "SELECT * FROM artifacts WHERE id = $1 AND revoked = false",
    [id]
  );
  return rows[0] ?? null;
}

export async function listArtifacts(userId: string): Promise<Artifact[]> {
  return query<Artifact>(
    "SELECT * FROM artifacts WHERE user_id = $1 AND revoked = false ORDER BY created_at DESC LIMIT 100",
    [userId]
  );
}

export async function revokeArtifact(id: string, userId: string): Promise<boolean> {
  const rows = await query<{ id: string }>(
    "UPDATE artifacts SET revoked = true WHERE id = $1 AND user_id = $2 RETURNING id",
    [id, userId]
  );
  return rows.length > 0;
}

// ── generators ────────────────────────────────────────────────────────────

/** Self-contained, print-friendly HTML document. */
export function toHtml(a: Artifact): string {
  const bodyHtml = marked.parse(a.body_md, { async: false }) as string;
  const safeTitle = escapeHtml(a.title);
  const when = new Date(a.created_at).toISOString().slice(0, 10);
  return `<!doctype html>
<html lang="en"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>${safeTitle} · CSL Atlas</title>
<style>
  :root { color-scheme: light; }
  body { font: 15px/1.65 -apple-system,Segoe UI,Roboto,Helvetica,Arial,sans-serif;
    max-width: 820px; margin: 40px auto; padding: 0 24px; color: #1a202c; }
  header { border-bottom: 2px solid #3a4ff7; padding-bottom: 12px; margin-bottom: 24px; }
  h1 { font-size: 24px; margin: 0 0 4px; color: #1a202c; }
  .meta { color: #718096; font-size: 12px; }
  h2 { font-size: 19px; margin-top: 28px; color: #3a4ff7; }
  h3 { font-size: 16px; color: #3a4ff7; }
  a { color: #3a4ff7; }
  code { background: #f0f2f7; padding: 2px 5px; border-radius: 4px; font-size: 13px; }
  pre { background: #f0f2f7; padding: 14px; border-radius: 8px; overflow-x: auto; }
  table { border-collapse: collapse; width: 100%; margin: 12px 0; }
  th,td { border: 1px solid #e2e8f0; padding: 6px 10px; text-align: left; }
  thead th { background: #f0f2f7; }
  blockquote { border-left: 3px solid #3a4ff7; margin: 12px 0; padding-left: 14px; color: #4a5568; }
  footer { margin-top: 40px; padding-top: 12px; border-top: 1px solid #e2e8f0;
    color: #a0aec0; font-size: 12px; }
  @media print { body { margin: 0; max-width: none; } }
</style></head>
<body>
  <header><h1>${safeTitle}</h1><div class="meta">CSL Atlas · graph-grounded research · ${when}</div></header>
  <main>${bodyHtml}</main>
  <footer>Generated by CSL Atlas. Verify source-cited facts before acting.</footer>
</body></html>`;
}

/** Word (.docx) document generated from the markdown body. */
export async function toDocxBuffer(a: Artifact): Promise<Buffer> {
  const children: Paragraph[] = [
    new Paragraph({ heading: HeadingLevel.TITLE, children: [new TextRun({ text: a.title })] }),
    new Paragraph({
      children: [new TextRun({ text: `CSL Atlas · ${new Date(a.created_at).toISOString().slice(0, 10)}`, italics: true, color: "718096" })],
    }),
    new Paragraph({ text: "" }),
    ...markdownToParagraphs(a.body_md),
  ];
  const doc = new Document({ sections: [{ children }] });
  return Packer.toBuffer(doc);
}

/** Pragmatic Markdown → docx paragraphs (headings, lists, bold, code). */
function markdownToParagraphs(md: string): Paragraph[] {
  const out: Paragraph[] = [];
  for (const rawLine of md.replace(/\r/g, "").split("\n")) {
    const line = rawLine.replace(/\s+$/, "");
    if (!line.trim()) {
      out.push(new Paragraph({ text: "" }));
      continue;
    }
    const h = line.match(/^(#{1,3})\s+(.*)$/);
    if (h) {
      const level = h[1].length;
      out.push(
        new Paragraph({
          heading:
            level === 1 ? HeadingLevel.HEADING_1 : level === 2 ? HeadingLevel.HEADING_2 : HeadingLevel.HEADING_3,
          children: inlineRuns(h[2]),
        })
      );
      continue;
    }
    const bullet = line.match(/^\s*[-*+]\s+(.*)$/);
    if (bullet) {
      out.push(new Paragraph({ bullet: { level: 0 }, children: inlineRuns(bullet[1]) }));
      continue;
    }
    const numbered = line.match(/^\s*\d+\.\s+(.*)$/);
    if (numbered) {
      out.push(new Paragraph({ numbering: { reference: "num", level: 0 }, children: inlineRuns(numbered[1]) }));
      continue;
    }
    out.push(new Paragraph({ children: inlineRuns(line) }));
  }
  return out;
}

/** Parse **bold** and `code` inline spans into docx TextRuns. */
function inlineRuns(text: string): TextRun[] {
  const runs: TextRun[] = [];
  const re = /(\*\*([^*]+)\*\*|`([^`]+)`)/g;
  let last = 0;
  let m: RegExpExecArray | null;
  while ((m = re.exec(text)) !== null) {
    if (m.index > last) runs.push(new TextRun({ text: text.slice(last, m.index) }));
    if (m[2] != null) runs.push(new TextRun({ text: m[2], bold: true }));
    else if (m[3] != null) runs.push(new TextRun({ text: m[3], font: "Consolas" }));
    last = m.index + m[0].length;
  }
  if (last < text.length) runs.push(new TextRun({ text: text.slice(last) }));
  return runs.length ? runs : [new TextRun({ text })];
}

function escapeHtml(s: string): string {
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}
