PROMPT_ANALYZE_ORGANIZATION_INPUT_KEY = "organization_name"
PROMPT_VERIFY_ORGANIZATION_NAME_INPUT_KEY = PROMPT_ANALYZE_ORGANIZATION_INPUT_KEY
PROMPT_VERIFY_ORGANIZATION_REALTIONSHIPS_INPUT_KEY = "organization_relationships"


DEFAULT_ORGANIZATION_TYPE = "ORGANIZATION"
ORGANIZATION_TYPES = {
    "COMPANY",
    "HOSPITAL",
    "UNIVERSITY",
    "NONPROFIT",
    "FOUNDATION",
    "GOVERNMENT",
    DEFAULT_ORGANIZATION_TYPE,
}
